### ISSUE TITLE
Country_of_Operator is ignored in Satellites analysis

### ISSUE THREAD

**Issue by zane** [OpenIQL/inferenceql.analyses#8]
❯ cat schema.edn
{"Type_of_Orbit" :nominal, "Inclination_radians" :ignore, "Period_minutes" :numerical, "Launch_Site" :nominal, "Country_of_Operator" :ignore, "Purpose" :nominal, "Users" :nominal, "Class_of_Orbit" :nominal, "Launch_Mass_kg" :ignore, "Eccentricity" :ignore, "Perigee_km" :numerical, "Apogee_km" :numerical}

**Comment by Schaechtle** [comment]
(forgot to close when it was fixed)
